version: '3'

services:
  web:
    build: .
    command: sh -c "python rent_car/manage.py migrate && python rent_car/manage.py runserver 0.0.0.0:8000"
    container_name: src
    volumes:
        - .:/src
    ports:
        - "8000:8000"